version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/default.int/prueba
permissions:
  - object: /var/www/default.int/prueba
    pattern: "*"
    owner: www-data
    group: www-data
    mode: 755
    type:
      - directory
  - object: /var/www/default.int/prueba
    pattern: "*"
    owner: www-data
    group: www-data
    mode: 644
    type:
      - file
